default: &default
 adapter:  postgresql
 pool:     5
 timeout:  5000
 encoding: unicode

development:
 <<: *default
 database: demo_project_development3
 username: postgres
 password: 'ubuntu'
 host:     localhost

test:
 <<: *default
 database: demo_project_test
 username: postgres
 password: 'ubuntu'
 host:     localhost
